database/models/database/__init__.py
"""Database base models"""

from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.instance import Instance


class DatabaseReplicationSystem(models.Model):
    """Database repliacation system model"""

    name = models.CharField("Name", max_length=9)
    system_id = models.CharField("Unique replication system identifier", max_length=64)

    class Meta:
        db_table = "database_database_replication_system"
        constraints = [
            models.UniqueConstraint(
                fields=["name", "system_id"],
                name="databasereplicationsystem_set_unique",
            )
        ]


# pylint: disable=R0903
class DatabaseManager(models.Manager):
    """Database manager"""

    def search(self, query=None):
        """Search for database"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by("name")
        return qs


class Database(models.Model):
    """Base database model"""

    name = models.CharField("Name of this database", max_length=128)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)
    cluster_id = models.CharField("Unique cluster identifier", max_length=64)

    instances = models.ManyToManyField(Instance)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = DatabaseManager()

    class Meta:
        db_table = "database_database"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["name", "cluster_id"], name="database_set_unique"
            )
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name} ({self.get_type_display()})"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracledatabase.get_absolute_url()  # pylint: disable=no-member

        return reverse("database:database-detail", kwargs={"pk": self.pk})

    def get_sites(self):
        """Return the site of servers hosting this database"""

        sites = []
        for instance in self.instances.all().select_related("server"):
            if instance.server.site not in sites:
                sites.append(instance.server.site)

        return sites

    def get_host(self):
        """Return a tuple of host type and host name"""

        server = self.instances.first().server

        # Don't want the FQDN, so split on "." and return first element
        if server.cluster:
            return ("cluster", server.cluster.name.split(".")[0])

        return ("cluster", server.name.split(".")[0])


class DatabaseSizeMetric(Metric):
    """Database size metric"""

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField("Total database size")
    datafile_size = models.PositiveBigIntegerField("Datafiles size")
    redo_size = models.PositiveBigIntegerField("Redo size")
    tempfile_size = models.PositiveBigIntegerField("Tempfiles size")

    class Meta(Metric.Meta):
        db_table = "database_database_size_metric"

database/models/diskgroup/__init__.py
from django.db import models

from core.models import Metric
from database.models.instance import Instance

class DiskgroupParameterMetric(Metric):
    """Diskgroup parameter metric model"""

    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    value = models.TextField('Value')

    class Meta(Metric.Meta):
        db_table = 'database_diskgroup_parameter_metric'
        ordering = ['name']

database/models/engine/__init__.py
from django.db import models
from django.urls import reverse

from system.models import Server

class Engine(models.Model):
    """Instance binary model"""

    path = models.CharField('Instance\'s binary', max_length=255)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    version = models.CharField('Version', max_length=255)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['path', 'server'], name='engine_set_unique')
        ]


    def __str__(self):
        return f"{self.path}"


    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('database:instancebinary-detail', kwargs={'pk': self.pk})

database/models/instance/__init__.py
"""Instance base models"""

from django.db import models
from django.urls import reverse

from core.models import Environment, Metric, Snapshot, Vendor
from database.models import DatabaseType
from database.models.engine import Engine
from system.models import Server


# pylint: disable=R0903
class InstanceManager(models.Manager):
    """Instance manager"""

    def search(self, query=None):
        """Search for instance"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs


class Instance(models.Model):
    """Base instance model"""

    name = models.CharField('Name', max_length=255)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE, blank=True, null=True)

    objects = InstanceManager()

    class Meta:
        db_table = 'database_instance'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'server'], name='instance_set_unique')
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name} ({self.get_type_display()})"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracleinstance.get_absolute_url()  # pylint: disable=no-member

        return reverse('database:instance-detail', kwargs={'pk': self.pk})


class InstanceParameterMetric(Metric):
    """Instance parameter metric model"""

    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    value = models.TextField('Value')

    class Meta(Metric.Meta):
        db_table = 'database_instance_parameter_metric'
        ordering = ['name']

database/models/tablespace/__init__.py
"""Tablespace base models"""

from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.database import Database


# pylint: disable=R0903
class TablespaceManager(models.Manager):
    """Tablepsace manager"""

    def search(self, query=None):
        """Search for tablespace"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Tablespace(models.Model):
    """Tablespace model"""

    name = models.CharField('Name', max_length=30)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = TablespaceManager()

    class Meta:
        db_table = 'database_tablespace'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'database'], name='tablespace_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracletablespace.get_absolute_url()  # pylint: disable=no-member


class TablespaceSpaceMetric(Metric):
    """Tablespace space metric"""

    tablespace = models.ForeignKey(Tablespace, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Size')
    used = models.PositiveBigIntegerField('Used')
    max_size = models.PositiveBigIntegerField('Max Size')

    class Meta(Metric.Meta):
        db_table = 'database_tablespace_space_metric'

database/models/tns/__init__.py
"""Tns base models"""

from django.db import models
from django.urls import reverse

from database.models.database import Database, DatabaseReplicationSystem
from database.models.database.oracle import ContainerOracleDatabase, OracleDatabase
from database.models.engine import Engine
from database.models.instance import InstanceParameterMetric
from system.models import Cluster, Server


class Listener(models.Model):
    """Listener model"""

    LOCAL = "LOCAL"
    SCAN = "SCAN"

    ORACLE_LISTENER_TYPE = [
        (LOCAL, "Local Listener"),
        (SCAN, "Scan Listener"),
    ]

    name = models.CharField("Name", max_length=30)
    type = models.CharField(max_length=5, choices=ORACLE_LISTENER_TYPE)
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)

    class Meta:
        db_table = "database_listener"

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == self.LOCAL:
            return self.locallistener.get_absolute_url()  # pylint: disable=no-member
        else:
            return self.scanlistener.get_absolute_url()  # pylint: disable=no-member


class LocalListener(Listener):
    """LocalListener model"""

    server = models.ForeignKey(Server, on_delete=models.CASCADE)

    class Meta:
        db_table = "database_listener_local"

    def save(self, *args, **kwargs):
        self.type = Listener.LOCAL
        super().save(*args, **kwargs)

    def __str__(self):
        """Return string representation"""
        return f"{self.name} (Local Listener)"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse("database:listener-local-detail", kwargs={"pk": self.pk})


class ScanListener(Listener):
    """ScanListener model"""

    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE)

    class Meta:
        db_table = "database_listener_scan"

    def save(self, *args, **kwargs):
        self.type = Listener.SCAN
        super().save(*args, **kwargs)

    def __str__(self):
        """Return string representation"""
        return f"{self.name} (SCAN Listener)"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse("database:listener-scan-detail", kwargs={"pk": self.pk})


class Endpoint(models.Model):
    """Endpoint model"""

    hostname = models.CharField("Hostname", max_length=255)
    port = models.PositiveSmallIntegerField("Port")

    listener = models.ForeignKey(Listener, on_delete=models.CASCADE)

    class Meta:
        db_table = "database_endpoint"


# pylint: disable=R0903
class ServiceManager(models.Manager):
    """Service manager"""

    def search(self, query=None):
        """Search for service"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by("name")
        return qs


class FailoverService(models.Model):
    """Failover Service Model"""

    name = models.CharField("Name", max_length=512)

    replication_system = models.ForeignKey(
        DatabaseReplicationSystem, on_delete=models.CASCADE
    )

    objects = ServiceManager()

    class Meta:
        db_table = "database_service_failover"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["name", "replication_system"],
                name="databaseservicefailover_set_unique",
            )
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse("database:failover-service-detail", kwargs={"pk": self.pk})

    @property
    def name_without_domain(self):
        """Return service name without db_domain"""
        return self.name.split(".")[0]

    @property
    def tns_name(self):
        """Unique tns name for this service"""
        sep = "-"
        return f"{self.replication_system.name}{sep}{self.name_without_domain}{sep}{self.replication_system.id}".replace(
            ".", "_"
        )

    @property
    def tns_string(self):
        """Return TNS string for this service"""
        connect_string = "(DESCRIPTION=(TRANSPORT_CONNECT_TIMEOUT=32)(CONNECT_TIMEOUT=60)(RETRY_COUNT=1)(ADDRESS_LIST=(FAILOVER=ON)"
        for service in self.service_set.all():
            connect_string += f"{service.tns_address}"
        connect_string += f"){self.tns_connect_data})"

        return connect_string

    @property
    def tns_connect_data(self):
        """Tns description for this service"""
        return f"(CONNECT_DATA=(SERVICE_NAME={self.name}))"


class Service(models.Model):
    """Service Model"""

    name = models.CharField("Name", max_length=512)
    hostname = models.CharField(
        "Hostname", max_length=255, null=True, blank=True, editable=False
    )
    port = models.PositiveSmallIntegerField(
        "Port", null=True, blank=True, editable=False
    )

    listeners = models.ManyToManyField(Listener)
    database = models.ForeignKey(Database, on_delete=models.CASCADE)

    failover_service = models.ForeignKey(
        FailoverService, on_delete=models.SET_NULL, null=True, blank=True
    )

    objects = ServiceManager()

    class Meta:
        db_table = "database_service"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["name", "database"], name="databaseservice_set_unique"
            )
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse("database:service-detail", kwargs={"pk": self.pk})

    @property
    def name_without_domain(self):
        """Return service name without db_domain"""
        return self.name.split(".")[0]

    @property
    def tns_name(self):
        """Unique tns name for this service"""
        sep = "-"
        return f"{self.database.name}{sep}{self.name_without_domain}{sep}{self.database.id}".replace(
            ".", "_"
        )

    @property
    def tns_string(self):
        """Return TNS string for this service"""
        return f"(DESCRIPTION={self.tns_address}{self.tns_connect_data})"

    @property
    def tns_address(self):
        """Tns description for this service"""
        return f"(ADDRESS=(PROTOCOL=TCP)(HOST={self.hostname})(PORT={self.port}))"

    @property
    def tns_connect_data(self):
        """Tns description for this service"""
        return f"(CONNECT_DATA=(SERVICE_NAME={self.name_without_domain}{self.db_domain}))"

    @property
    def db_domain(self):
        """Return database domain"""
        instance = self.database.instances.first()
        db_domain = InstanceParameterMetric.objects.filter(
            instance=instance.id, name="db_domain", snapshot=instance.snapshot_id
        )

        if len(db_domain) == 1:
            return f".{db_domain[0].value}"
        return ""


class NetworkAliasManager(models.Manager):
    """Service manager"""

    def search(self, query=None):
        """Search for service"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by("name")
        return qs


class NetworkAlias(models.Model):
    """Base Network alias model"""

    name = models.CharField("Name", max_length=512)

    objects = NetworkAliasManager()

    class Meta:
        db_table = "database_alias_network"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["name"], name="databasenetworkalias_set_unique"
            )
        ]


class StandaloneNetworkAlias(NetworkAlias):
    """Network alias Model"""

    service = models.ForeignKey(Service, on_delete=models.CASCADE)

    class Meta:
        db_table = "database_alias_network_standalone"

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse(
            "database:standalone-network-alias-detail", kwargs={"pk": self.pk}
        )


class FailoverNetworkAlias(NetworkAlias):
    """Failover network alias Model"""

    service = models.ForeignKey(FailoverService, on_delete=models.CASCADE)

    class Meta:
        db_table = "database_alias_network_failover"

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse("database:failover-network-alias-detail", kwargs={"pk": self.pk})

database/templates/database/oracle/database_detail_cdb.html
{% extends "database/oracle/database_detail_container.html" %}
{% block container_type %}Multitenant CDB database{% endblock %}

database/templates/database/oracle/database_detail_leg.html
{% extends "database/oracle/database_detail_container.html" %}
{% block container_type %}Legacy database{% endblock %}

database/templates/database/oracle/database_detail_pdb.html
{% extends "database/database.html" %}
{% load mathfilters %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<h1>Pluggable database</h1>
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>DBID</th>
            <td>{{ object.dbid }}</td>
        </tr>
        <tr>
            <th>Size</th>
            <td>{{ object.size | filesizeformat }}</td>
        </tr>
        <tr>
            <th>Creation date</th>
            <td>{{ object.created }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-instances-tab" data-bs-toggle="pill" data-bs-target="#pills-instances" type="button" role="tab" aria-controls="pills-instances" aria-selected="true">Instances</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-tablespaces-tab" data-bs-toggle="pill" data-bs-target="#pills-tablespaces" type="button" role="tab" aria-controls="pills-tablespaces" aria-selected="false">Tablespaces</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-users-tab" data-bs-toggle="pill" data-bs-target="#pills-users" type="button" role="tab" aria-controls="pills-users" aria-selected="false">Users</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-replication-tab" data-bs-toggle="pill" data-bs-target="#pills-replication" type="button" role="tab" aria-controls="pills-replication" aria-selected="false">Dataguard</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-services-tab" data-bs-toggle="pill" data-bs-target="#pills-services" type="button" role="tab" aria-controls="pills-services" aria-selected="false">Services</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-instances" role="tabpanel" aria-labelledby="pills-instances-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Instance</th>
                    <th>Server</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for instance in object.instances.all %}
                <tr>
                    <td><a href="{{ instance.get_absolute_url }}">{{ instance }}</a></td>
                    <td><a href="{{ instance.server.get_absolute_url }}">{{ instance.server }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-tablespaces" role="tabpanel" aria-labelledby="pills-tablespaces-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Tablespace</th>
                    <th>Usage</th>
                    <th>Size</th>
                    <th>Used</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for tablespace in tablespaces %}
                {% widthratio tablespace.size_metric.used tablespace.size_metric.size 100 as used_percent %}
                <tr>
                    <td><a href="{{ tablespace.get_absolute_url }}">{{ tablespace.name }}</a></td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-label="Tablespace usage" style="width: {{ used_percent }}%;" aria-valuenow="{{ used_percent }}" aria-valuemin="0" aria-valuemax="100">{{ used_percent }}%</div>
                        </div>
                    </td>
                    <td>{{ tablespace.size_metric.size | filesizeformat }}</td>
                    <td>{{ tablespace.size_metric.used | filesizeformat }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-users" role="tabpanel" aria-labelledby="pills-users-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>User</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for user in oracle_users %}
                <tr>
                    <td><a href="{{ user.get_absolute_url }}">{{ user }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-replication" role="tabpanel" aria-labelledby="pills-replication-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Database</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for database in object.replication_system.database_set.all %}
                <tr>
                    <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
                    <td>{{ database.database_role }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-fra" role="tabpanel" aria-labelledby="pills-fra-tab" tabindex="0">
        <div class="w-50">
            <canvas id="fraSpace"></canvas>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-services" role="tabpanel" aria-labelledby="pills-services-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Services</th>
                    <th>TNS Alias</th>
                    <th>TNS Failover Alias</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for service in object.services_set.all %}
                <tr>
                    <td><a href="{{ service.get_absolute_url }}">{{ service }}</a></td>
                    <td>{% for alias in service.networkalias_set.all %}
                        <a href="{{ alias.get_absolute_url }}">{{ alias }}</a>{% endfor %}
                    </td>
                    <td>{% for failover_alias in service.failover_service.failovernetworkalias_set.all %}
                        <a href="{{ failover_alias.get_absolute_url }}">{{ failover_alias }}</a>{% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

database/templates/database/oracle/instance-oracle-asm-detail.html
{% extends "database/instance.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Environment</th>
            <td>{{ object.environment }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Version</th>
            <td>{{ object.engine.version }}</td>
        </tr>
        <tr>
            <th>Oracle Home</th>
            <td>{{ object.engine }}</td>
        </tr>
        <tr>
            <th>Server</th>
            <td><a href="{{ object.server.get_absolute_url }}">{{ object.server }}</a></td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Diskgroups</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Parameters</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for diskgroup in object.oraclediskgroup_set.all %}
                <tr>
                    <td><a href="{{ diskgroup.get_absolute_url }}">{{ diskgroup }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for metric in instance_metrics %}
                <tr> <!-- # {{ parameter.id }} -->
                    <td>{{ metric.name }}</td>
                    <td>{{ metric.value }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

database/templates/database/oracle/instance-oracle-database-detail.html
{% extends "database/instance.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Environment</th>
            <td>{{ object.environment }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Version</th>
            <td>{{ object.engine.version }}</td>
        </tr>
        <tr>
            <th>Oracle Home</th>
            <td>{{ object.engine }}</td>
        </tr>
        <tr>
            <th>Server</th>
            <td><a href="{{ object.server.get_absolute_url }}">{{ object.server }}</a></td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Databases</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Parameters</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for database in object.database_set.all %}
                <tr>
                    <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for metric in instance_metrics %}
                <tr> <!-- # {{ parameter.id }} -->
                    <td>{{ metric.name }}</td>
                    <td>{{ metric.value }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}